config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index new create show destroy] do
      resources :comments, only: %i[new create destroy]
      resources :likes, only: %i[new create]
  end
end
  root to: 'users#index'
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can :read, Post, public: true
    return unless user.present? # additional permissions for logged in users (they can read their own posts)

    can :read, Post, user: user
    can :manage, Post, user: user # only post owners can manage posts
    can :manage, Comment, user: user # only post owners can manage posts
    return unless user.admin? # additional permissions for administrators

    can :manage, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post, counter_cache: :comments_counter
  after_save :update_comments_count
  after_destroy :update_comments_count

  private

  def update_comments_count
    post.update(comments_counter: post.comments.size)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user, class_name: 'User',
                    foreign_key: 'author_id'
  belongs_to :post, counter_cache: :likes_counter

  after_save :update_likes_count
  after_destroy :update_likes_count

  private

  def update_likes_count
    post.update!(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, class_name: 'User',
                    foreign_key: 'author_id',
                    counter_cache: :posts_counter
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  after_save :update_posts_count
  after_destroy :update_posts_count

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, :likes_counter, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0
  }
  def most_recent_five_comments
    comments.includes(:user).order(created_at: :desc).limit(5)
  end

  private

  def update_posts_count
    user.update(posts_counter: user.posts.size)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy
  validates :posts_counter, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0
  }
  validates :name, presence: true
  def most_recent_three_posts
    posts.order(created_at: :desc).limit(3)
  end
  # Roles = [ :admin , :default ]

  def admin?
    # role == requested.role.to_s
    :role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password posts_counter])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[show edit update destroy]
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show; end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit; end

  # POST /comments or /comments.json
  def create
    user = User.find(params[:user_id])
    post = Post.find(params[:post_id])
    puts user, post.comments_counter
    comment = params[:comment]
    new_comment = Comment.new(comment.permit(:text))
    new_comment.author_id = user.id
    new_comment.post_id = post.id
    if new_comment.save
      redirect_to user_post_url(user, post)
    else
      render :new
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def comment_params
    params.require(:comment).permit(:text)
  end

  def destroy
    @comment = Comment.find(params[:comment_id])
    @post = Post.find(@comment.post_id)
    @post.comments_counter -= 1
    @comment.destroy!
    @post.save
    flash[:success] = 'You have deleted this comment successfully!'
    redirect_to user_post_path(current_user.id, @comment.post_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_like, only: %i[show edit update destroy]

  # GET /likes or /likes.json
  def index
    @likes = Like.all
  end

  # GET /likes/1 or /likes/1.json
  def show; end

  # GET /likes/new
  def new
    @like = Like.new
  end

  # GET /likes/1/edit
  def edit; end

  def create
    @post = Post.includes(:user).find(params[:post_id])
    @post_author = @post.user

    @the_user = current_user

    @liked_posts_by_this_user = Like.where(user: @the_user, post: @post)

    destroy && return if @liked_posts_by_this_user.present?

    new_like = Like.create(user: @the_user, post: @post)

    return unless new_like.save

    flash[:notice] = 'You liked this post.'
    redirect_back_or_to user_post_url(@post_author, @post)
  end

  def destroy
    @liked_posts_by_this_user.destroy_all
    flash[:notice] = 'You removed your like from this post.'
    redirect_back_or_to user_post_url(@post_author, @post)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_like
    @like = Like.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def like_params
    params.fetch(:like, {})
  end
end

app/controllers/post_controler.rb
class PostsController < ApplicationController
  def index
    ###
  end

  def show
    ####
  end
end

app/controllers/posts_controler.rb
class PostsController < ApplicationController
  def index
    ###
  end

  def show
    ####
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    author_id = params[:user_id]
    @user = User.find(author_id)
    @posts = Post.includes(:user).where(user: params[:user_id])
  end

  def show
    @post = Post.includes(:user, comments: [:user]).find(params[:id])
  end

  def create
    post = params[:post]
    user = User.find(params[:user_id])
    new_post = Post.new(post.permit(:title, :text))
    new_post.comments_counter = 0
    new_post.likes_counter = 0
    new_post.author_id = user.id

    if new_post.save
      flash[:notice] = 'New post created successfully.'
      redirect_to user_post_url(user, new_post)
    else
      flash[:error] = 'Creating new post failed!'
      @post = new_post
      render :new
    end
  end

  def new
    @post = Post.new
    render :new
  end

  def destroy
    @post = Post.find(params[:post_id])
    @post.tuu
    @post.destroy
    flash[:success] = 'Post successfully deleted'
    redirect_to("/users/#{current_user.id}/posts/")
  end
end

app/controllers/users_controler.rb
class UsersController < ApplicationController
  def index
    ###
  end

  def show
    ####
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @recent_posts = @user.most_recent_three_posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Text:</strong>
    <%= comment.text %>
  </p>

</div>

app/views/comments/_form.html.erb
<div class="container">
<%= form_with model: comment, url: user_post_comments_url(author_id, post), class: 'form' do |f| %>
  <%= f.text_area :text,style:"width:100%" %>
  <br>
  <%= f.submit "Comment" %>
<% end %>
</div>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>       
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/likes/_form.html.erb
<%= form_with model: like, url: user_post_likes_url(user, post), method: :post, class: 'inline' do |f| %>
  <%= f.submit "#{post.likes_counter || 0} Likes" %>
<% end %>

app/views/likes/_like.html.erb
<div id="<%= dom_id like %>">
</div>

app/views/likes/edit.html.erb
<h1>Editing like</h1>

<%= render "form", like: @like %>

<br>

<div>
  <%= link_to "Show this like", @like %> |
  <%= link_to "Back to likes", likes_path %>
</div>

app/views/likes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Likes</h1>

<div id="likes">
  <% @likes.each do |like| %>
    <%= render like %>
    <p>
      <%= link_to "Show this like", like %>
    </p>
  <% end %>
</div>

<%= link_to "New like", new_like_path %>

app/views/likes/new.html.erb
<h1>New like</h1>

<%= render "form", like: @like %>

<br>

<div>
  <%= link_to "Back to likes", likes_path %>
</div>

app/views/likes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @like %>

<div>
  <%= link_to "Edit this like", edit_like_path(@like) %> |
  <%= link_to "Back to likes", likes_path %>

  <%= button_to "Destroy this like", @like, method: :delete %>
</div>

app/views/posts/_post.html.erb
<div class="card mt-4 p-4">
 <h2>
    <span>Post #<%=  %></span>
    <span>
      <%= link_to post.title, [post.user, post] %> 
    </span>
  </h2>
   <p>
    <%= post.text %>
  </p>
  <div class="d-flex justify-content-end">
  <small>
    <span>Comment: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></span>
  </small>
  
  </div>
</div>

app/views/posts/_post_details.html.erb
<div class="container">
<div class="post">
  <div class="comment-header">
    <h2>
      Post by <%= post.user.name %>
    </h2>
    <small>
      <span>Comment: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></span>
    </small>
  </div>
  <p>
    <%= post.text %>
  </p>
   <%= render partial: "likes/form", locals: { like: Like.new, user: post.user, post: post } %>
</div>
<% if can? :destroy, @post %>
    <%= button_to 'Delete Post', "/users/#{params[:user_id]}/posts/#{@post.id}",  data: { "turbo-method": :delete , "turbo-confirm": "Are you sure?" }, class: "btn text-white btn-danger delete-post" %>
  <% end %> 
<div class="comments-wrapper">
  <h3>Comments:</h3>
  <% if @post.comments.empty? %>
    <p>There no comment so far!</p>
  <% end %>
  <% @post.comments.each do |comment| %>
    <div class="comment-card">
      <strong>
        <%= link_to user_path(comment.author_id) do %>
          <%= comment.user.name %>
        <% end %>
        :
      </strong>
      <%= comment.text %>
    </div>
       <% if can? :destroy, @post %>
    <%= button_to 'Delete Comment', "/users/#{params[:user_id]}/posts/#{@post.id}",  method: :delete, class: "btn text-white btn-danger" %>
  <% end %>
  <% end %>

  <h3>Add new comment:</h3>
  <%= render partial: "comments/form", locals: { comment: Comment.new, author_id: @post.author_id, post: @post } %>
</div>
</div>

app/views/posts/index.html.erb
 <%= render partial: "users/user" , locals: { user: @user } %>
 
<div class="container">
  <% @posts.each_with_index do |post, index| %>
    <%= render partial: "post" , locals: { post: post, index: index } %>
      <ul>
        <% post.comments.each do |comment| %>
          <li>
            <%= render partial: "shared/comment" , locals: { comment: comment } %>
          </li>
          <% end %>
      </ul>
      <% end %>
      <%= link_to "comment", "/new" %>
</div>

app/views/posts/new.html.erb
<h1 class="text-center" >Create new post</h1> 
<div class="container d-flex justify-content-center">

<%= form_with model: @post, url: user_posts_url, method: :post, class: 'form' do |f| %>
  <%= f.label :title, 'Title',style:"with:100%" %>
  <%= f.text_field :title,style:"width:100%" %>
  <%= f.label :text, 'Content' ,style:"width:100%" %>
  <%= f.text_area :text ,style:"width:100%" %>
  <%= f.submit "Save" %>
<% end %>
</div>

app/views/posts/show.html.erb
<div>
  <%= render partial: "post_details" , locals: { post: @post } %>
  
</div>

<div class="posts"></div>

app/views/shared/_comment.html.erb
<span>
  <%= comment.user.name %>: <%= comment.text %>
</span>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block,width:100%" %>
    <%= form.text_field :name,style: "width:100%" %>
  </div>

  <div>
    <%= form.label :bio, style: "display: block" %>
    <%= form.text_area :bio,style: "width:100%" %>
  </div>

  <div>
    <%= form.label :photo, style: "display: block" %>
    <%= form.text_field :photo,style: "width:100%" %>
  </div>

  <div class="mt-4">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<%= link_to user do %>
<div class="container mt-4">
<div class="card" id="users">
  <div class="row">
    <div class="col-lg-4">
    <%= image_tag("user.png", :alt => "rss feed", class: 'img-fluid rounded-start')   %>

    </div>
    <div class="col-lg-8">
      <h2>
      <%= user.name %>
    </h2>
    <div class="d-flex w-100 justify-content-end p-3">
    <small>
      Number of posts: <%= user.posts_counter %>
    </small>
    </div>
    
    </div>
  </div>
</div>
</div>
</div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<%= render @users %>

app/views/users/new.html.erb
<div class="container mt-4 d-flex justify-content-center">
<div class="row">
  <div class="col-lg-3"></div>
  <div class="col-lg-6"></div>
  
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>
</div>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>
<div class="container">
<div class="card mt-4 p-4">
  <h4>Bio</h4>
  <p class="text-muted">
    <%= @user.bio %>
  </p>
</div>
<div>
 <div>
    <% @recent_posts.each do |post, index| %>
      <%= render partial: "posts/post" , locals: { post: post, index: index } %>
        <% end %>
  </div>
  <div class="d-flex justify-content-center">
    <%= link_to "New post", new_user_post_path(@user) %>
 <%= link_to "See all posts" , user_posts_path(@user) if @user.posts_counter> 0 %>

  </div>
</div>
</div>
</div>